### ISSUE TITLE
Add support for 1D DWT

### ISSUE THREAD

**Issue by fbcotter** [fbcotter/pytorch_wavelets#11]
As requested in #6

**Comment by MushroomHunting** [comment]
Hi Fergal,

Thanks so much for this library! I was just wondering if there has been any development on the 1D transform as I am interested in experimenting with the WT for audio analysis and the pywt based solution I have is quite slow - particularly for processing larger numbers of signals 

cheers

**Comment by CDitzel** [comment]
I think it is rather simple since the 1D transform is already included within the 2D transform

**Comment by LittleFlyingSheep** [comment]
Excuse me, I have seen the answer about #6, but still have problem to use your code to achieve DWT for a 1-D audio signal. Would you please show a example about 1-D audio signal?  Thank you very much for your work.

**Comment by fbcotter** [comment]
@LittleFlyingSheep `master` now has support for 1d transforms. see the readme for an example
