### ISSUE TITLE
License

### ISSUE THREAD

**Issue by davidplpl** [fbcotter/pytorch_wavelets#12]
What is the license of this repo?
Thanks

**Comment by fbcotter** [comment]
Just added an MIT License

**Comment by fbcotter** [comment]
If you are using the DTCWT section of the repo, you should see the License at the bottom of the README.rst, in particular the request to cite Nick Kingsbury's [paper](https://royalsocietypublishing.org/doi/pdf/10.1098/rsta.1999.0447). If you only wish to use the DWT, then the MIT license applies, but please cite the DOI for now (until I release a paper).
