### ISSUE TITLE
Is the SWT avaliable now? Is there something wrong in the SWTInverse under the current version?

### ISSUE THREAD

**Issue by yeelinsen** [fbcotter/pytorch_wavelets#15]
Hi, @fbcotter .When I used the SWTForward in transpose2d.py and SWTInverse in swt_inverse.py, I found that the output of SWTInverse with input(N, 4C, H, W) has a shape of N*C*2H*2W. Shouldn't it be the shape (N, C, H, W) ? Thank u for this helpful repository and the great effort you've paid!

**Comment by fbcotter** [comment]
Hi @yeelinsen, the SWT implementation in my repo is very untested. I'd like to properly sit down and make it work nicely. I think the Inverse SWT has many possible options too, as it's a redundant transform, and I haven't yet chosen which to implement

**Comment by yeelinsen** [comment]
Thank you for your patient apply!
