### ISSUE TITLE
A problem about multiple GPUs training.

### ISSUE THREAD

**Issue by freepoet** [fbcotter/pytorch_wavelets#27]
Hi,fbcotter. I'm very interested in your dissertation and this github repo.</br>
I met a problem when I called _DTCWTForward()_. </br>
Can _DTCWTForward()_ support  training on multiple GPUs. I want to _import pytorch_wavelets_ , and then train CNN on 8 GPUS .</br>
Thx!!!

**Comment by fbcotter** [comment]
Hi @freepoet, sorry for not getting back to you! Yes it should support this naturally as the classes all inherit from `torch.nn.Module` did you manage to get it working?

**Comment by Mojzaar** [comment]
I have the same problem. When I want to use DWTForward as down-sampling layer inside of my model, the resultant output would remain on the cpu! While, I have used the pytorch Dataparallel to move the entire of the model on multiple GPUs. Any suggestion?
