### ISSUE TITLE
about image size

### ISSUE THREAD

**Issue by taozhuang123** [fbcotter/pytorch_wavelets#4]
Forgive me for being a newbie, I would like to ask, if my input image size is odd, after DWT, IDWT, how can I get the same size. Thank you very much, if you can give me any answer.

**Comment by fbcotter** [comment]
Hi @taozhuang123, you can just take the top left corner of the output image. For example:

```python
import torch
from pytorch_wavelets import DWT, IDWT
import numpy as np
fwd = DWT(J=2, wave='db2')
inv = IDWT(wave='db2')

# Declare an odd sized input
x = torch.randn(5,6,29,29)
y = fwd(x)
z = inv(y)
print(z.shape)
>>> (5, 6, 30, 30)
np.testing.assert_array_almost_equal(x, z[:, :, :-1, :-1])
```

**Comment by taozhuang123** [comment]
Thank you very much,this is very helpful to me.
