### ISSUE TITLE
using dtcwt as a high freq feature extractor

### ISSUE THREAD

**Issue by jamesrobertwilliams** [fbcotter/pytorch_wavelets#41]
I would like to extract high frequency components of an image and I am wondering how I can extract this using dtcwt. So, I looked at the examples, and I presume I can do something like this:

```
import torch, sys
from pytorch_wavelets import DTCWTForward
xfm1 = DTCWTForward(J=3)
x = torch.randn(1, 3, 64, 64) # 3 channel 64x64 img example
yl, yh = xfm1(x)
print(yl.shape)
print(len(yh),yh[0].shape)
```

I presume here yl and yh are low and high frequency components respectively. However, I see that the HF components are complex :(

I guess my question is, how do I (in a sensible way) get a 1D flattened real vector (amplitude?) from the `yh` components.

Apologies if this is daft question and thank you ever so much for this awesome package.

**Comment by fbcotter** [comment]
Hi @jamesrobertwilliams, sorry for the slow reply! The best way to get the real high frequency components is to take the absolute value of the complex coefficients. 

The real and imaginary parts are both DWTs, so it would also work to take either of these, but at edge boundaries the real and imaginary both oscillate and the magnitude of these is less stable - see problem 2 on page 2 of http://sigproc.eng.cam.ac.uk/foswiki/pub/Main/NGK/sp_mag_finalsub.pdf.
