### ISSUE TITLE
How to change default tensor dtype in pytorch_wavelets

### ISSUE THREAD

**Issue by zxyl1003** [fbcotter/pytorch_wavelets#47]
I want to use torch.float16 data type when DWT, but i got a error:
```
RuntimeError: expected scalar type Half but found Float
```
I think the reason is that the data type of the DWT function is torch.float32, but input data type is torch.float16. Is there any way to change the default torch.float32 type of the DWT function to torch.float16.

**Comment by abeyang00** [comment]
Use pytorch_wavelets.DWTForward(wave='haar').to(torch.float16)

**Comment by zxyl1003** [comment]
Thank you!

**Comment by GiYeolKim** [comment]
what a great idea!
thank you so much
