### ISSUE TITLE
1d discrete wavelet transform

### ISSUE THREAD

**Issue by doublejtoh** [fbcotter/pytorch_wavelets#6]
I want to forward 4d input tensor with 1d discrete wavelet transform through specific axis(e.g Channel axis). Is there any api for it or should i implement for it?

**Comment by fbcotter** [comment]
Interesting that you want to do it along the channel axis. 

It is certainly possible to do the 1-D transforms along the final two axes by calling `afb1d` and `sfb1d` in `pytorch_wavelets.dwt.lowlevel`. Note that you may want to wrap this in a `torch.autograd.Function` to make it memory efficient (you can see my implementation of `AFB2D` for an example of this.

Doing it along the channel axis would require reshaping, as the lowlevel convolution functions in pytorch don't work along the channel dimension.

I can help you with this if you get into difficulties.

**Comment by fbcotter** [comment]
I assume this was ok for you to do in the end. Let me know if you need help still.

**Comment by picagrad** [comment]
Hi @fbcotter , first off thanks a bunch for this. 
I might need a similar thing to this original feature request, though with slight differences.
I am trying to implement a loss based on sparsity in the 1D-DWT domain, so in my case I would need a 1 dimensional implementation in the shaping of the inputs as-well. Basically I want to have something like:
L(Y) = L_0(Y) + ||DWT(Y)||_1
Where Y is an output of a convolutional network, and thus its shape (N,1,L) where N is the batch size and L is the number of timesteps (length).

Will the suggested workaround still work, or does 'pytorch_wavelets.dwt.lowlevel' only take NCHW images? (of course I could always unsqueeze and squeeze back potentially)

**Comment by fbcotter** [comment]
Hi @picagrad, they do currently only take 4-D tensors but it would be free to do the reshaping. I might add support for the 1-D DWT as it's been requested twice now.

**Comment by picagrad** [comment]
Hi, thanks for the reply!

I actually realised that using the multi-resolution method, it's quite
simple to create the 1D-DWT in pytorch simply using two simple strides
convolutions, one for the detail and one for the lowpass. I implemented
that, and it seems to work well.

Thanks for the help!

**Comment by wahyubram82** [comment]
@picagrad : so, we just:
`torch.Tensor(np.vstack(lowpass,detail))`
for the similar level?
