### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by mariakesa** [fbcotter/pytorch_wavelets#7]
Hello:-)

I installed the package using pip install . in an Anaconda Environment, but when I try to import pytorch_wavelets in a jupyter notebook running with the same environment I get an error. 
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-18-20092c7621f4> in <module>
     17 import tqdm
     18 #from PyTorchWavelets import *
---> 19 import pytorch_wavelets
     20 from pytorch_wavelets import DWTForward
     21 

ModuleNotFoundError: No module named 'pytorch_wavelets'

Help would be appreciated:-)

Thank you,
Maria

**Comment by mariakesa** [comment]
It doesn't work in pycharm either.

**Comment by mariakesa** [comment]
Sorry my bad! I messed up libraries!

**Comment by fbcotter** [comment]
No problems. I assume I can close this issue then?

**Comment by mariakesa** [comment]
Thank you! Yes!
