### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by Prasanna1991** [fbcotter/pytorch_wavelets#8]
Is there any way to cite this library? Do you have any preference?

**Comment by fbcotter** [comment]
Hi @Prasanna1991, I'm glad you've found my repo helpful! I currently don't have any paper describing it, but have been meaning to write a paper doing so.

I'll put one on arXiv in a week or two and update this thread when I have.

**Comment by Prasanna1991** [comment]
Thanks!

**Comment by asberk** [comment]
Thank you for the helpful package, @fbcotter . I may soon need to cite `pytorch_wavelets`, too. Another option is to make the [repository itself citable](https://guides.github.com/activities/citable-code/).

**Comment by fbcotter** [comment]
Thanks @asberk. I've made a DOI for the meantime which you can cite.

**Comment by fbcotter** [comment]
I've updated the readme now, I think the best thing to cite is my PhD thesis, which describes this work in chapter 3: https://doi.org/10.17863/CAM.53748
