### ISSUE TITLE
Is SWT avaliable now?

### ISSUE THREAD

**Issue by IceClear** [fbcotter/pytorch_wavelets#9]
Hi, @fbcotter, thanks for your wonderful work. I am now trying to use SWT and I found it in transform2d.py. Is it avaliable now?

**Comment by fbcotter** [comment]
Hi @IceClear, the SWT forward transform is in the code, but I never finished doing the inverse SWT. Because I never finished this, I never made it neat, but it should work. 

It would be great to hear how you want to use the SWT.

**Comment by IceClear** [comment]
OK. Thanks again for your patient reply and your great work.
